title: "The Folded Elephant"
description: "Sentiments that don't require a trip to the store."
baseurl: "" 
url: "https://thefoldedelephant.com"

#Snipcart Settings
apikey: "NWNiY2M0YjAtZTE3Yi00NjFlLWEyMWEtZDcyYTllNzRmNTA2NjM2OTQ0ODUzODIxNzU5NjQ3"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

